### ISSUE TITLE
npm run build 失败，npm run dev成功

### ISSUE THREAD

**Issue by chebysheph** [XBT1/v-contextmenu#12]
error in static/js/vendor.5402823ca7092e4b41d2.js from UglifyJs
Unexpected token: punc (() [./~v-contextmenu/dist/index.common.js:7,0][static/js/vendor.5402832ca7092e4b41d2.js:67101,7])

检查了一下，是main.js中的引入导致build报错：
import contextmenu from 'v-contextmenu';
但是dev没有报错，注释掉上面这句再build也没有报错，去掉注释再build就报错，这到底是什么原因

**Comment by XBT1** [comment]
生产环境请不要对 `v-contextmenu/dist/index.common.js` 做 Uglify 操作

**Comment by XBT1** [comment]
可以参考 https://github.com/ElemeFE/element/issues/5176

``` javascript
module: {
    rules:[
       {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test'),resolve('/node_modules/element-ui/src'),resolve('/node_modules/element-ui/packages')]
      },
   ]
}
```
