### ISSUE TITLE
 除了click事件可以消失右键菜单外，是否也需要加个contextmenu（其他列）事件也要消失

### ISSUE THREAD

**Issue by shengrongchun** [XBT1/v-contextmenu#13]

**Comment by XBT1** [comment]
暂时可以通过 `this.$refs.contextmenu.hide()` 来手动隐藏，下个版本会加入自动隐藏

**Comment by XBT1** [comment]
`v2.2.0` 版本已加入 `Contextmenu` 显示时，关闭其它 `Contextmenu` 的功能
