### ISSUE TITLE
Dynamic context menu attribute

### ISSUE THREAD

**Issue by Max64** [XBT1/v-contextmenu#20]
I need to enable context menu based on variable value, tried like this but this doesn't work:

`:v-contextmenu:contextmenu="enableMenu"`

Is it possible anyway?

**Comment by XBT1** [comment]
Nonsupport now. Maybe next version will support this feature. 1 or 2 days later.

**Comment by XBT1** [comment]
It's recommended to use `v-for` to dynamically generate `MenueItem`. Here's some problems to support dynamic `ContextMenu` with dynamic directive.

**Comment by sunchenguang** [comment]
why can not support Dynamic context menu attribute.
in some case, maybe need this feature
