### ISSUE TITLE
关于右击菜单定位

### ISSUE THREAD

**Issue by Mr-KeyboardHero** [XBT1/v-contextmenu#21]
请教一个问题，就是如果我的内容比较多，需要滚动条往下拉，我一旦拉到下面的内容，右击菜单，菜单定位会到点击位置的右上角，我的菜单比较长，看起来比较丑，怎么调整让菜单一直定位在鼠标点击位置的右下角

**Comment by XBT1** [comment]
这样的话菜单不就益处浏览器窗口了吗？

**Comment by Mr-KeyboardHero** [comment]
你的考虑很有道理，但是我的菜单选项比较多如果反过来就很奇怪，而且屏幕是可以往下滚动的，如果我一旦滚动了，不管点击哪里菜单都是定位在鼠标右上角，我应该在哪里调整这个设定呢，谢谢大佬！

**Comment by XBT1** [comment]
v2.4.0 已支持
`<v-contextmenu ref="contextmenu" :auto-placement="false"></v-contextmenu>`

**Comment by josephvong** [comment]
> v2.4.0 已支持
> `<v-contextmenu ref="contextmenu" :auto-placement="false"></v-contextmenu>`

我也遇到了 右键菜单里面 内容过多的情况，在某些情况下，右键菜单上面的内容会溢出浏览器的顶部浏览范围。如果设置为“:auto-placement="false"” 的话有些体验也不太好。 建议在 设置“contextmenuPosition.top” 的时候，可以和 0 做个比较，如果 小于0 直接取0
