### ISSUE TITLE
无法知道打开的是哪个div的右键菜单

### ISSUE THREAD

**Issue by moqingliang** [XBT1/v-contextmenu#23]
`<v-contextmenu ref="contextmenu">`
  `<v-contextmenu-item>添加</v-contextmenu-item>`
`</v-contextmenu>`

`<div id="box-1" v-contextmenu:contextmenu>用户</div>`
`<div id="box-2" v-contextmenu:contextmenu>部门</div>`

多个div绑定同一个contextmenu时：
如以上代码：当我右键“部门”的div打开菜单，点击添加，此时无法知道到底是点击了“用户”还是“部门”的div。也就是说handleClick (vm, event)事件只返回了contextmenu对象和鼠标事件，并没有返回div对象。

**Comment by XBT1** [comment]
当两个 `Contextmenu` 功能不一样时，建议写两个，而不是共用一个。
`ContextmenuItem` 本身在 `click` 时并不能很方便的知道是被哪个元素触发的。后续可能会在 `Contextmenu` 的 `show` 事件的参数中附上触发元素。

**Comment by XBT1** [comment]
现在可以通过监听 `contextmenu` 事件来获取你需要的数据了

**Comment by snokier** [comment]
`click` 回调中添加触发区域的 `VNode` 会导致组件复杂度提高很多且此参数不应归 `click` 所有，在 `contextmenu` 中给出此参数也是经过了一些考虑的。后续可能考虑增加一个 `getOrigin` 之类的方法供获取触发区域的 `VNode`。现在还是请使用 `contextmenu` 事件自行记录吧。

**Comment by lpk25** [comment]
> contextmenu事件是出菜单的时候吧。这个不太准确。不能再click回调里加个参数吗，比如有一种场景，我div是v-for出来的。需要右键菜单删除某个div，现在就无法定位到。 @snokier

您好，这个问题 最后怎么解决的呢
