### ISSUE TITLE
菜单隐藏事件监听有误

### ISSUE THREAD

**Issue by z1769057083** [XBT1/v-contextmenu#26]
<contextmenu ref="contextmenu" @show="doShow" @hide="doHide" :theme="theme">
    <contextmenu-item @click="doClick">刷新</contextmenu-item>
      <contextmenu-submenu title="新增节点">
        <contextmenu-item @click="openNewSubNode">新增子节点</contextmenu-item>
        <contextmenu-item>批量新增子节点</contextmenu-item>
        <contextmenu-item>新增前一节点</contextmenu-item>
        <contextmenu-item>新增后一节点</contextmenu-item>
      </contextmenu-submenu>
    <contextmenu-item>编辑节点属性</contextmenu-item>
    <contextmenu-submenu title="删除节点">
      <contextmenu-item>删除当前节点</contextmenu-item>
      <contextmenu-item>删除子节点</contextmenu-item>
    </contextmenu-submenu>
    <contextmenu-submenu title="移动节点">
      <contextmenu-item>向上移动</contextmenu-item>
      <contextmenu-item>向下移动</contextmenu-item>
      <contextmenu-item>节点迁移</contextmenu-item>
    </contextmenu-submenu>
  </contextmenu>

**Comment by z1769057083** [comment]
如上hide事件 在菜单显示的时候就执行了，鼠标左键点击空白区域菜单隐藏，但是hide事件并没有执行，请问我想获得隐藏事件怎么办呢？

**Comment by z1769057083** [comment]
已定位原因，通过vuex去触发右键菜单的显示隐藏，鼠标点击区域没有被捕获到，已改源码

**Comment by XaviLv** [comment]
Hi, 我今天也发现了这个问题。能尽快发布吗？呵呵，我们好npm i 
Thanks

**Comment by XBT1** [comment]
新版本已经优化了 `show/hide` 事件，可以尝试一下
