### ISSUE TITLE
hide事件未能正常触发

### ISSUE THREAD

**Issue by khty2000** [XBT1/v-contextmenu#29]
在使用中，使用v-contextmenu:ref指令，绑定了hide事件，代码如下：
<v-contextmenu ref="contextmenu" @show="rightMenuShowHandle" @hide="rightMenuHideHandle">
  <v-contextmenu-item @click="copyLogInfo">复制该行数据</v-contextmenu-item>
  <v-contextmenu-item divider></v-contextmenu-item>
  <v-contextmenu-item @click="saveLogInfoImg">存为图片</v-contextmenu-item>
</v-contextmenu>
    rightMenuShowHandle (vm) {
      console.log('show event')
    },
    rightMenuHideHandle (vm) {
      console.log('hide event')
    },
在实际使用中，如果点击弹出菜单项，比如"复制该行数据"引发菜单关闭的话，会正常触发hide事件，但如果是点击菜单外的地方，引发菜单关闭，则hide事件并不触发。

**Comment by XBT1** [comment]
在使用哪个版本？

**Comment by khty2000** [comment]
使用的是2.4.0版本，更新到2.5.0，bug没有了。多谢
