### ISSUE TITLE
文档问题

### ISSUE THREAD

**Issue by caoxiaoshuai1** [XBT1/v-contextmenu#4]
东西是好东西
文档有点不详细了
main.js 不支持 v-contextmenu 这种写法。
建议支持vContextmenu

**Comment by XBT1** [comment]
首先感谢你的反馈 :)

请问 `main.js 不支持 v-contextmenu 这种写法。建议支持vContextmenu` 是指？

在即将发布的 2.0 版本中将会添加支持 [`Vue.use(contextmenu)` 这样的写法](https://github.com/XBT1/v-contextmenu/blob/2.0-dev/examples/main.js)

**Comment by hwp82316** [comment]
Vue2.5.2
vue.esm.js?efeb:574 [Vue warn]: Error in directive contextmenu bind hook: "TypeError: Cannot read property '$refs' of undefined"
是咋回事呢

**Comment by XBT1** [comment]
@hwp82316 请问使用的 `v-contextmenu` 哪个版本？

**Comment by xxx135261** [comment]
如何局部的引入？
