### ISSUE TITLE
v-contextmenu如何局部引入？

### ISSUE THREAD

**Issue by xxx135261** [XBT1/v-contextmenu#7]

**Comment by 1490738306** [comment]
同求,全局引入后打包报错

**Comment by XBT1** [comment]
@xxx135261 @1490738306 可以尝试一下

``` javascript
import {
  Contextmenu,
  ContextmenuItem,
  ContextmenuSubmenu,
  ContextmenuGroup,
} from 'v-contextmenu'
```

但是样式还是需要单独引入的

**Comment by XBT1** [comment]
@1490738306 请问全局引入报了什么错误？

**Comment by 1490738306** [comment]
*{
        margin: 0;
        padding: 0;
    }
    font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
npm ERR! code ELIFECYCLEnpm ERR! errno 2npm ERR! iview-admin@1.2.1 build: `webpack --progress --hide-modules --config build/webpack.prod.config.js`npm ERR! Exit status 2npm ERR!npm ERR! Failed at the iview-admin@1.2.1 build script.npm ERR! This is probably not a problem with npm. There is likely additional logging output above.



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                    发自网易邮箱大师                


    在2018年2月6日 14:04，XBTop1!<notifications@github.com> 写道： 


@1490738306 请问全局引入报了什么错误？

**Comment by XBT1** [comment]
这看起来是 `iview-admin` webpack 配置的问题？

**Comment by XBT1** [comment]
@1490738306 稍等我会提供给你一个单独引用的 demo。

**Comment by 1490738306** [comment]
*{
        margin: 0;
        padding: 0;
    }
    font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
我使用的是iview官方的模板,应该不会有问题吧;我刚刚学习vue两个月,对vue还是不太熟悉,请见谅但是我还是非常感谢您的热心帮助,我在这里提前祝您新春快乐



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                    发自网易邮箱大师                


    在2018年2月6日 14:15，XBTop1!<notifications@github.com> 写道： 


@1490738306 稍等我会提供给你一个单独引用的 demo。

**Comment by XBT1** [comment]
@1490738306 v2.1.0 版本中支持组件的单独引入，示例可见 #10

**Comment by 1490738306** [comment]
*{
        margin: 0;
        padding: 0;
    }
    font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
生产环境请不要对 v-contextmenu/dist/index.common.js 做 Uglify 操作可以在 babel-loader 中配置能给我个例子,怎么操作吗



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                    发自网易邮箱大师                


    在2018年2月6日 14:21，1490738306<1490738306@qq.com> 写道： 




    *{
        margin: 0;
        padding: 0;
    }
    font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
我使用的是iview官方的模板,应该不会有问题吧;我刚刚学习vue两个月,对vue还是不太熟悉,请见谅但是我还是非常感谢您的热心帮助,我在这里提前祝您新春快乐



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                    发自网易邮箱大师                


    在2018年2月6日 14:15，XBTop1!<notifications@github.com> 写道： 


@1490738306 稍等我会提供给你一个单独引用的 demo。

**Comment by XBT1** [comment]
@1490738306 #12
